services:
  jc-bot:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: jc-bot

    restart: no

    working_dir: /app

    env_file:
      - /config/.env

    environment:
      - NODE_ENV=production

    volumes:
      - jcbot_data:/app/config:rw

    # If your bot needs network access:
    network_mode: bridge

volumes:
  jcbot_data:
    name: jcbot_data
