services:
  jc-bot:
    container_name: jc-bot
    build: .
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./jc-bot_data/config:/config:rw
      - ./jc-bot_data/data:/data:ro
    env_file:
      - ./jc-bot_data/config/.env
    environment:
      - NODE_ENV=production
