services:
  jc-bot:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: jc-bot

    restart: no

    working_dir: /app

    environment:
      - NODE_ENV=production

    volumes:
      - /srv/ssd/containers/jc-bot_data:/app/data
      - /srv/ssd/containers/jc-bot_data/.env:/app/.env:ro

    # If your bot needs network access:
    network_mode: bridge
